name: Release (golang.go-nightly)

# Daily release on 15:00 UTC, monday-thursday.
<<<<<<< HEAD
# Or, trigger with workflow dispatch event.
on:
  schedule:
    - cron: "0 15 * * MON-THU"  # 15 UTC, monday-thursday daily
  workflow_dispatch:
=======
# Or, force to release by triggering repository_dispatch events by using
#   curl -v -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/golang/vscode-go/dispatches -d '{ "event_type": "force-release" }'
on:
  schedule:
    - cron: "0 15 * * MON-THU"  # 15 UTC, monday-thursday daily
  repository_dispatch:
    types: [force-release]
>>>>>>> origin/dev.go2go

jobs:
  release:
    if: github.ref == 'refs/heads/master' && github.repository == 'golang/vscode-go'

    name: Release Nightly
    runs-on: ubuntu-latest
<<<<<<< HEAD
    environment: nightly
=======
>>>>>>> origin/dev.go2go
    timeout-minutes: 20

    steps:
      - name: Clone repository
<<<<<<< HEAD
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
         node-version: '18'
         cache: 'npm'

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
         go-version: '1.20'
         check-latest: true
         cache: true
=======
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
         go-version: '1.14'
>>>>>>> origin/dev.go2go

      - name: Install dependencies
        run: npm ci

      - name: Prepare Release
        run: build/all.bash prepare_nightly

<<<<<<< HEAD
      - name: Version
        run: |
          echo "VSCODE_GO_VERSION=$(jq .version package.json | tr -d '"')" >> $GITHUB_ENV

      - name: Package Extension
        run: npx vsce package -o "./go-nightly-${{ env.VSCODE_GO_VERSION }}.vsix"

      - name: Compile
        run: npm run vscode:prepublish

      # TODO: use prerelease versions of tools (how? or master?)

      - name: Install Go tools (Modules mode)
        run: |
            go run ./tools/installtools/main.go
        env:
          GO111MODULE: on
          EXT: "${{ matrix.os == 'windows-latest' && '.exe' || ''}}"
=======
      - name: Compile
        run: npm run vscode:prepublish

      - name: Install Go tools (Modules mode)
        run: |
            go version
            go get github.com/acroca/go-symbols \
               github.com/davidrjenni/reftools/cmd/fillstruct \
               github.com/haya14busa/goplay/cmd/goplay \
               github.com/mdempsky/gocode \
               github.com/sqs/goreturns \
               github.com/uudashr/gopkgs/v2/cmd/gopkgs \
               github.com/zmb3/gogetdoc \
               golang.org/x/lint/golint \
               golang.org/x/tools/cmd/gorename \
               golang.org/x/tools/gopls

        env:
          GO111MODULE: on

      - name: Install Go tools (GOPATH mode)
        run: |
          go version
          go get github.com/cweill/gotests/... \
            github.com/rogpeppe/godef \
            github.com/ramya-rao-a/go-outline
            # Because some tests depend on the source code checked in GOPATH. TODO: FIX THEM.
        env:
          GO111MODULE: off

>>>>>>> origin/dev.go2go

      - name: Run unit tests
        run: npm run unit-test

      - name: Run tests
<<<<<<< HEAD
        run: xvfb-run -a npm run test
=======
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test
>>>>>>> origin/dev.go2go
        env:
          CODE_VERSION: 'insiders'
          VSCODEGO_BEFORE_RELEASE_TESTS: true

      - name: Publish
        if: github.ref == 'refs/heads/master' && github.repository == 'golang/vscode-go'
<<<<<<< HEAD
        run: |
          echo "publishing ${{ env.VSCODE_GO_VERSION }}"
          ls *.vsix
          npx vsce publish -i "./go-nightly-${{ env.VSCODE_GO_VERSION }}.vsix" -p "${{ secrets.VSCE_TOKEN }}"
=======
        uses: lannonbr/vsce-action@704da577da0f27de5cdb4ae018374c2f08b5f523
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
>>>>>>> origin/dev.go2go
